export class EncryptionManager {
    private static instance: EncryptionManager
    private roomKeys: Map<string, CryptoKey> = new Map()

    // Constants
    private static readonly ALGORITHM = "AES-GCM"
    private static readonly KEY_LENGTH = 256

    static getInstance(): EncryptionManager {
        if (!EncryptionManager.instance) {
            EncryptionManager.instance = new EncryptionManager()
        }
        return EncryptionManager.instance
    }

    /**
     * Generates a new random key for a room.
     * In a real app, this would be generated by the creator and shared securely (e.g., via RSA public keys).
     * For this demo, we'll derive it from a "shared secret" or just generate one and assume it's shared.
     */
    async generateKey(): Promise<CryptoKey> {
        return window.crypto.subtle.generateKey(
            {
                name: EncryptionManager.ALGORITHM,
                length: EncryptionManager.KEY_LENGTH,
            },
            true, // extractable
            ["encrypt", "decrypt"]
        )
    }

    /**
     * Derives a key from a password (e.g., Room Password).
     * This ensures all users with the password can generate the same key.
     */
    async deriveKeyFromPassword(password: string, salt: Uint8Array): Promise<CryptoKey> {
        const enc = new TextEncoder()
        const keyMaterial = await window.crypto.subtle.importKey(
            "raw",
            enc.encode(password),
            "PBKDF2",
            false,
            ["deriveKey"]
        )

        return window.crypto.subtle.deriveKey(
            {
                name: "PBKDF2",
                salt: salt.buffer as ArrayBuffer,
                iterations: 100000,
                hash: "SHA-256",
            },
            keyMaterial,
            { name: EncryptionManager.ALGORITHM, length: EncryptionManager.KEY_LENGTH },
            false, // not extractable (more secure)
            ["encrypt", "decrypt"]
        )
    }

    /**
     * Sets the key for a specific room.
     */
    setRoomKey(roomId: string, key: CryptoKey) {
        this.roomKeys.set(roomId, key)
    }

    getRoomKey(roomId: string): CryptoKey | undefined {
        return this.roomKeys.get(roomId)
    }

    /**
     * Encrypts text data.
     * Returns format: "iv:ciphertext" (Base64 encoded)
     */
    async encrypt(text: string, roomId: string): Promise<string> {
        const key = this.roomKeys.get(roomId)
        if (!key) {
            console.warn(`No encryption key for room ${roomId}, sending as plain text`)
            return text
        }

        const iv = window.crypto.getRandomValues(new Uint8Array(12))
        const enc = new TextEncoder()
        const encoded = enc.encode(text)

        const cipherBuffer = await window.crypto.subtle.encrypt(
            {
                name: EncryptionManager.ALGORITHM,
                iv: iv,
            },
            key,
            encoded
        )

        const cipherArray = new Uint8Array(cipherBuffer)
        const ivBase64 = this.arrayBufferToBase64(iv)
        const cipherBase64 = this.arrayBufferToBase64(cipherArray)

        return `enc::${ivBase64}::${cipherBase64}`
    }

    /**
     * Decrypts text data.
     * Expects format: "enc::iv::ciphertext"
     */
    async decrypt(encryptedText: string, roomId: string): Promise<string> {
        if (!encryptedText || !encryptedText.startsWith("enc::")) {
            return encryptedText // Not encrypted
        }

        const key = this.roomKeys.get(roomId)
        if (!key) {
            console.warn(`No encryption key for room ${roomId}, cannot decrypt`)
            return "[Locked Message]"
        }

        try {
            const parts = encryptedText.split("::")
            if (parts.length !== 3) throw new Error("Invalid encrypted format")

            const iv = this.base64ToArrayBuffer(parts[1])
            const cipher = this.base64ToArrayBuffer(parts[2])

            const decryptedBuffer = await window.crypto.subtle.decrypt(
                {
                    name: EncryptionManager.ALGORITHM,
                    iv: new Uint8Array(iv),
                },
                key,
                new Uint8Array(cipher)
            )

            const dec = new TextDecoder()
            return dec.decode(decryptedBuffer)
        } catch (e) {
            console.error("Decryption failed:", e)
            return "[Decryption Error]"
        }
    }

    // --- Helpers ---

    private arrayBufferToBase64(buffer: ArrayBuffer | Uint8Array): string {
        let binary = ""
        const bytes = new Uint8Array(buffer)
        const len = bytes.byteLength
        for (let i = 0; i < len; i++) {
            binary += String.fromCharCode(bytes[i])
        }
        return window.btoa(binary)
    }

    private base64ToArrayBuffer(base64: string): ArrayBuffer {
        const binary_string = window.atob(base64)
        const len = binary_string.length
        const bytes = new Uint8Array(len)
        for (let i = 0; i < len; i++) {
            bytes[i] = binary_string.charCodeAt(i)
        }
        return bytes.buffer
    }

    /**
     * Encrypts a binary buffer.
     */
    async encryptBuffer(buffer: ArrayBuffer, roomId: string): Promise<Uint8Array> {
        const key = this.roomKeys.get(roomId)
        if (!key) throw new Error("No encryption key for room")

        const iv = window.crypto.getRandomValues(new Uint8Array(12))
        const cipherBuffer = await window.crypto.subtle.encrypt(
            {
                name: EncryptionManager.ALGORITHM,
                iv: iv,
            },
            key,
            buffer
        )

        // Combine IV and Ciphertext
        const combined = new Uint8Array(iv.length + cipherBuffer.byteLength)
        combined.set(iv)
        combined.set(new Uint8Array(cipherBuffer), iv.length)

        return combined
    }

    /**
     * Decrypts a binary buffer.
     */
    async decryptBuffer(combinedBuffer: ArrayBuffer, roomId: string): Promise<ArrayBuffer> {
        const key = this.roomKeys.get(roomId)
        if (!key) throw new Error("No encryption key for room")

        const iv = new Uint8Array(combinedBuffer.slice(0, 12))
        const ciphertext = combinedBuffer.slice(12)

        return await window.crypto.subtle.decrypt(
            {
                name: EncryptionManager.ALGORITHM,
                iv: iv,
            },
            key,
            ciphertext
        )
    }
}
